apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: stage-workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in application releases. Refer to https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest for the expected format
metadata:
  stages/v1alpha1:
    - name: QA
      jobs:
        - QA
        - test
        - test-3
jobs:
  QA:
    uses: test-cdro-prod/prod-python-hello-world/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['prod-python-hello-world']['cbpautomation/python-hello-world-docker'].id }}
      environment: QA
  test:
    needs: QA
    runs-on:
      - default
      - Label1
      - Label2
    environment: ecr-qa
    steps:
      - name: test step
        uses: cloudbees-io/snyk-sast-plugin@v1
        with:
          snyk-token: b805f82c-36ef-4f7d-aee5-16bfaa718f75
          org-id: cloudbees-compliance-partner-development
        kind: scan
  test-3:
    needs:
      - test
    runs-on: hari
    environment: ecr-qa
    steps:
      - name: test-step
        kind: build
        uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: PLAYWRIGHT
          results-path: test_report.xml
